title: Medipeli for Developers
description: Developer guideline for Medipeli.
theme: just-the-docs

url: https://medipeli.github.io/developer

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
