export const hospitalTypes = [
  "General Hospital",
  "Specialty Hospital",
  "Children's Hospital",
  "Psychiatric Hospital",
  "Rehabilitation Center",
  "Teaching Hospital",
  "Private Clinic",
  "Surgical Center",
  "Dental Clinic",
  "Eye Clinic",
  "Fertility Clinic",
  "Orthopedic Hospital",
  "Cardiology Hospital",
  "Oncology Center",
  "Cosmetic Surgery Clinic",
];

export const hospitalFacilities = [
  "24/7 Emergency Services",
  "Inpatient Services",
  "Outpatient Services",
  "Intensive Care Unit",
  "Radiology and Imaging",
  "Laboratory Services",
  "Pharmacy",
  "Physiotherapy",
  "Maternity Services",
  "Surgical Services",
  "Dialysis",
  "Dental Services",
  "Cardiology Services",
  "Oncology Services",
  "Plastic Surgery",
  "Translation Services",
  "Patient Transportation",
  "Accommodation Assistance",
  "Medical Concierge",
  "Travel Insurance Assistance",
];
